### ISSUE TITLE
Video Issues

### ISSUE THREAD

**Issue by ntableman** [beele/homebridge-unifi-protect-camera-motion#11]
Using a docker container with FFMPEG: oznu/homebridge

1 - enabling audio causes ffmpeg exit code 1 and nothing happens. Is there a way I can debug this?

2 - video generally doesnt seem to work: it sends a still every 15-30 seconds. I have tinkered with bitrate/fps/size to see if I can speed this up, but no luck.

homebridge is on an ubuntu full intel (no rpi, diskstation, etc...) on gigabit ethernet.

**Comment by ntableman** [comment]
fixed 2, needed to remove all the throttling parameters

**Comment by beele** [comment]
Have you compiled FFMpeg with support for audio?

**Comment by beele** [comment]
@ntableman 
Another option (if audio is the problem) is to force the audio codec:
"audio": true, "acodec": "libopus"
