### ISSUE TITLE
[Unifi protect cameras & motion sensors] Cannot get cameras: Error: ERROR: Could not enumerate motion sensors: Error: Authentication failed: {}

### ISSUE THREAD

**Issue by andrewoke** [beele/homebridge-unifi-protect-camera-motion#16]
Getting this error. It was previously working and I'm not sure what changed during an update. I've verified I can login with the user I provided etc. etc. Turning debug to true doesn't seem to increase logging though.

**Comment by andrewoke** [comment]
`
        {
            "platform": "Unifi-Protect-Camera-Motion",
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "controller": "https://unifi:7443",
                "controller_rtsp": "rtsp://unifi:7447",
                "username": "***",
                "password": "***",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": true,
                "enhanced_motion_score": 50,
                "enhanced_classes": [
                    "person"
                ],
                "debug": true,
                "save_snapshot": true
            },
            "videoConfig": {
                "vcodec": "h264",
                "audio": false,
                "maxStreams": 2,
                "maxWidth": 3840,
                "maxHeight": 2160,
                "maxFPS": 30,
                "mapvideo": "0:1",
                "mapaudio": "0:0"
            }
        },
`

**Comment by alvaroledesma** [comment]
I am also having this issue

**Comment by andrewoke** [comment]
I'm glad it's not just me haha. I thought I must have missed something.

Protect version is 1.13.1

**Comment by andrewoke** [comment]
Ok, so I didn't catch it the first time, but ubuntu's resolvconf was messing with dns. I basically had to disable it, add my dns server in and now it's working again. You should be able to check that unifi-protect actually resolves to the cloudkey.

**Comment by alvaroledesma** [comment]
>Ok, so I didn't catch it the first time, but ubuntu's resolvconf was messing with dns. I basically had to disable it, add my dns server in and now it's working again. You should be able to check that unifi-protect actually resolves to the cloudkey.

@andrewoke suggestions on how to do that? I can’t tell if it’s my firewall or the DNS on the homebridge controller 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrewoke** [comment]
Well, from wherever you run homebridge you should be able to resolve your cloud keys dns name. If not then you have a dns problem, otherwise it's something else.
