### ISSUE TITLE
Streaming quality at 640x360@132kBit and maxFPS seems stuck at 15

### ISSUE THREAD

**Issue by scoobaspeaz** [beele/homebridge-unifi-protect-camera-motion#17]
How can I increase this? I also set my maxFPS to 30fps (G3 Bullet is 30fps)

Also I notice my streaming quality is stuck at 640x360@132kBit when I look at homebridge logs. How can I increase this? I have the RTSP stream at High 1920x1080. I even tried Medium 1024x526. 
[Unifi protect cameras & motion sensors] Start streaming video from Driveway with 640x360@132kBit

 "videoConfig": {
                "vcodec": "h264_omx",
                "audio": "true",
                "maxStreams": 2,
                "maxWidth": 1024,
                "maxHeight": 576,
                "maxFPS": 30,
                "mapvideo": "0:1",
                "mapaudio": "0:0",
                "maxBitrate": 8000,
                "packetSize": 376,
                "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"

**Comment by scoobaspeaz** [comment]
Video quality has changed dramatically by using the codec copy instead of h264_omx as mentioned here: https://github.com/beele/homebridge-unifi-protect-camera-motion/issues/15#issuecomment-586013388

Im going to continue to test this to see if it helps. Nothing above has changed as far as the streaming quality 640x360@132kBit but at least the picture seems smoother now.

**Comment by scoobaspeaz** [comment]
Welp never mind on that. I woke up this morning to the video not wanting to stream with the copy vcodec option. I had to put it back to h264_omx to get it to stream. However streaming is 1 frame per few seconds. Its horrible that way.

Wonder why copy isn't working anymore?

**Comment by beele** [comment]
These stream values are requested by the iOS device, only an ipad can request a 720p stream.
