### ISSUE TITLE
Publish Motion to MQTT

### ISSUE THREAD

**Issue by nzbullet** [beele/homebridge-unifi-protect-camera-motion#21]
Just wondered if you've thought about adding MQTT support to publish motion activity. This would make it possible to interact with the camera motion for other plugins that use MQTT (e.g. mine) ;)

There is [Unifi Protect MQTT](https://github.com/noodlemctwoodle/unifi-video-mqtt) this which I have installed on my Cloudkey but would prefer to not install something on the Cloudkey and seeing as you get the messages anyway it would just be a case of publishing them to a configured MQTT broker.

**Comment by beele** [comment]
I have no experience with MQTT.
Feel free to add this and open a PR

**Comment by beele** [comment]
homebridge-camera-ffmpeg is adding mqtt support in the future.
Once that is release I'll see if this can easily be implemented in this plugin

**Comment by beele** [comment]
This will be coming in the next release

**Comment by beele** [comment]
This is now available with the 0.4.3 release
