### ISSUE TITLE
Tidy up log messages

### ISSUE THREAD

**Issue by nzbullet** [beele/homebridge-unifi-protect-camera-motion#23]
Any chance you could remove all the extra's from the logs? Even when debug is not enabled there is a lot of info clogging up the logs. For example strings with !!!! at the start and end and the event ID's. Realistically this should only be shown if the debug is enabled. 

I have this currently...
<img width="1325" alt="Screenshot 2020-03-31 at 150546" src="https://user-images.githubusercontent.com/24196566/77979444-2f408180-7361-11ea-8886-5064879b4457.png">

But this looks much cleaner...
<img width="803" alt="Screenshot 2020-03-31 at 150559" src="https://user-images.githubusercontent.com/24196566/77979476-40898e00-7361-11ea-80e2-3f6c1fe7ea87.png">

**Comment by beele** [comment]
I will have a look at this!
