### ISSUE TITLE
Get Verified

### ISSUE THREAD

**Issue by a-rodriguez** [beele/homebridge-unifi-protect-camera-motion#30]
I would not consider this a high priority but wanted to suggest making this a "[Verified](https://github.com/homebridge/homebridge/wiki/verified-Plugins)" plugin.

**Comment by beele** [comment]
I will have a look at this, however installing the plugin can be troublesome on some devices due to the dependency on tensorflowjs

**Comment by beele** [comment]
- The plugin must successfully install. ***On macos/windows/linux, and rbpi, docker/synology is problematic***
- The plugin must implement the Homebridge Plugin Settings GUI. ***TODO***
- The plugin must not start unless it is configured. ***New homebridge does this automatically***
- The plugin must not execute postinstall scripts that modify the users system in any way. ***postinstall only rebuilds npm dependency***
- The plugin must not contain any analytics or calls that enable the plugin developer to track you. ***no tracking!***
- The plugin must not throw unhandled exceptions, the plugin must catch and log it's own errors. ***to be double checked***
- The plugin must be published to npm and the source code available on GitHub. ***done***
- The plugin must run on all Active LTS versions of Node.js, at the time of writing this is Node.js v10 and v12. ***done***
- The plugin must not require the user to run Homebridge in a TTY or with non-standard startup parameters, even for initial configuration. ***done***
- If the plugin needs to write files to disk (cache, keys, etc.), it must store them inside the Homebridge storage directory. ***mostly done, saved snapshots to user dir for now, to be fixed***

**Comment by beele** [comment]
- https://www.npmjs.com/package/homebridge-unifi-protect-camera-motion/v/0.2.0-beta.6
- install with: npm i homebridge-unifi-protect-camera-motion@0.2.0-beta.6

**Comment by beele** [comment]
Latest beta (with a lot of fixes & improvements):
- https://www.npmjs.com/package/homebridge-unifi-protect-camera-motion/v/0.2.1-beta.5
- install with: npm i homebridge-unifi-protect-camera-motion@0.2.1-beta.5 -g --unsafe-perm=true

**Comment by beele** [comment]
Opened an issue to get the plugin verified: https://github.com/homebridge/verified/issues/72

**Comment by beele** [comment]
Done!

**Comment by a-rodriguez** [comment]
Thank you for all the hard work!
