### ISSUE TITLE
Plugin incorrectly using Platform Name instead of Plugin Identifier

### ISSUE THREAD

**Issue by nzbullet** [beele/homebridge-unifi-protect-camera-motion#32]
Although the plugin is working, I am receiving this error in my logs.

`[5/7/2020, 08:44:20] One of your plugins incorrectly registered an external accessory using the platform name (Unifi-Protect-Camera-Motion) and not the plugin identifier. Please report this to the developer!`

**Comment by beele** [comment]
This will be fixed once my reworked version is released.
Working on a fully typescript version & better integration with the newer homebridge 1.x.x release.

**Comment by beele** [comment]
Will be in a future release.
