### ISSUE TITLE
problem saving image on class detection

### ISSUE THREAD

**Issue by ntableman** [beele/homebridge-unifi-protect-camera-motion#37]
[5/12/2020, 9:09:35 PM] [Unifi Protect] person detected (95%) by camera Front Doorbell !!!!
(node:14223) UnhandledPromiseRejectionWarning: Cannot save image to disk: ENOENT: no such file or directory, open '/root/.homebridge/snapshot-2020-05-13T01:09:35.839Z.jpg'
(node:14223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

also...would be cool if somehow the class was passed to the alert on homekit, but dont know how...or if there was an MQTT hook somehow.

> {
>             "name": "Unifi Protect",
>             "unifi": {
>                 "enhanced_classes": [
>                     "person",
>                     "car",
>                     "dog",
>                     "truck",
>                     "cat"
>                 ],
>                 "controller": "https://unifi:7443",
>                 "controller_rtsp": "rtsp://unifi:7447",
>                 "username": "adsfasdfasdffff",
>                 "password": "dfadsfad",
>                 "motion_interval": 5000,
>                 "motion_repeat_interval": 30000,
>                 "motion_score": 50,
>                 "enhanced_motion": true,
>                 "enhanced_motion_score": 50,
>                 "save_snapshot": true,
>                 "debug": false
>             },
>             "googlePhotos": {
>                 "upload_gphotos": false,
>                 "auth_redirectUrl": "http://localhost:8080/oauth2-callback"
>             },
>             "videoConfig": {
>                 "audio": true,
>                 "maxStreams": 4,
>                 "preserveRatio": "W",
>                 "maxFPS": 30,
>                 "mapvideo": "0:1",
>                 "mapaudio": "0:0",
>                 "packetSize": 376
>             },
>             "platform": "UnifiProtectMotion"
>         }

**Comment by beele** [comment]
Where is your homebridge folder? It look like you are running homebridge as root (but homebridge probably is installed in the user folder)

**Comment by beele** [comment]
Try the latest build, this has improvements for this (0.3.3)
