### ISSUE TITLE
Cannot get cameras: Error: ERROR: Could not enumerate motion sensors: Error: Authentication failed: {}

### ISSUE THREAD

**Issue by maloo0** [beele/homebridge-unifi-protect-camera-motion#38]
Hi everyone,

I am getting the following error.

_[Unifi protect cameras & motion sensors] Initializing UnifiProtectMotion platform...
[Unifi protect cameras & motion sensors]  Endpoint Style: Unifi Protect (Legacy)
[Unifi protect cameras & motion sensors]  WARNING: No previous session foung, a new session must be created!
[Unifi protect cameras & motion sensors]  Cannot get cameras: Error: ERROR: Could not enumerate motion sensors: Error: Authentication failed: {}_

**No cameras are disappearing in Apple Home.
The raspberry was set up new today.
My Config:**

_{
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "enhanced_classes": [
                    "person"
                ],
                "controller": "https://192.168.1.1:7443/",
                "controller_rtsp": "rtsp://192.168.1.1:7447",
                "username": "test",
                "password": "testtest",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": true,
                "enhanced_motion_score": 50,
                "save_snapshot": true,
                "debug": false
            },
            "videoConfig": {
                "maxStreams": 2,
                "maxWidth": 1024,
                "maxHeight": 576,
                "maxFPS": 15,
                "vcodec": "h264_omx",
                "mapvideo": "0:1",
                "mapaudio": "0:0",
                "audio": true
            },
            "platform": "UnifiProtectMotion"
        }_

**Hope, someone could help me!
Thanks!**

**Comment by beele** [comment]
You should not put a / behind the controller url

**Comment by maloo0** [comment]
Hi beele,

Thanks a lot!
That was the fault.

Now it's working fine with the following config: 
(Maybe it could help someone)


_{
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "enhanced_classes": [
                    "person"
                ],
                "controller": "https://192.168.1.1:7443",
                "controller_rtsp": "rtsp://192.168.1.1:7447",
                "username": "username",
                "password": "password",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": true,
                "enhanced_motion_score": 50,
                "save_snapshot": true,
                "debug": false
            },
            "videoConfig": {
                "vcodec": "h264_omx",
                "audio": true,
                "maxStreams": 2,
                "maxWidth": 1080,
                "maxHeight": 720,
                "maxFPS": 30,
                "mapvideo": "0:1",
                "mapaudio": "0:0",
                "maxBitrate": 3000,
                "packetSize": 1316,
                "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
            },
            "platform": "UnifiProtectMotion"
 }_


Only the quality of the stream in Home App isn't so great. Is there any possibility to improve this?

And I still have one problem:
The motions are not recognized very quick and not always. So my light, I want to put on with the motion sensor of my camera, puts on too late. 
Also sometimes it doesn't recognize motion, although unify protect pushes a message.
How can I solve this? By adding more "enhanced_classes"?

Thanks!

**Comment by beele** [comment]
The quality is hard to improve since ios requests a low bitrate stream. I'm still looking for a way to improve this although I don't know if it's event possible.

You could disable the enhanced motion detection, or play with the detection thresholds (both in the config and in the protect UI)

**Comment by maloo0** [comment]
Thanks for your response again!

Would be nice, if you could improve it sometime.
But first, I am happy that it‘s working at all.

I‘ve disabled enhanced motion detection. It‘s much better now. I am still playing around a little :)

Thanks for all
