### ISSUE TITLE
TensorFlow binary was not compiled to use: AVX2 FMA

### ISSUE THREAD

**Issue by jirajared** [beele/homebridge-unifi-protect-camera-motion#45]
Wondering if you could point me in the right direction. Followed your guide to the T incl switching to the :ubuntu docker release.
Currently using an Intel NUC but getting the following error:
`Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`

Is there a way to re-compile TensorFlow to include AVX2 FMA?

**Comment by beele** [comment]
There is a way, but it is out of scope of this project due to the complexity involved.
