### ISSUE TITLE
Streaming freeze in HomeKit app

### ISSUE THREAD

**Issue by matellis** [beele/homebridge-unifi-protect-camera-motion#47]
Got everything working and setup. Snapshots are working fine. Streaming however results in a spinner showing in the middle of the video on the HomeKit app and no active video, just the last snapshot. On the homebridge end you see streaming successfully starting and stopping. In debug mode, you see it running at speed around 1x (sometimes 1.01x) for the precise time the video feed is open.

What am I missing? Config below. I've tried messing about with maxbitrate and max width/height. 

```
        {
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "enhanced_classes": [
                    "person",
                    "car",
                    "truck"
                ],
                "controller": "https://172.16.1.3:7443",
                "controller_rtsp": "rtsp://172.16.1.3:7447",
                "username": "XXXXXXXX",
                "password": "XXXXXXXXX",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": true,
                "enhanced_motion_score": 50,
                "save_snapshot": false,
                "debug": false
            },
            "googlePhotos": {
                "upload_gphotos": false,
                "auth_redirectUrl": "http://localhost:8080/oauth2-callback"
            },
            "videoConfig": {
                "maxStreams": 2,
                "maxWidth": 1024,
                "maxHeight": 576,
                "maxFPS": 15,
                "maxBitrate": 30000,
                "vcodec": "libx264",
                "packetSize": 376,
                "audio": false,
                "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
            },
            "platform": "UnifiProtectMotion"
        }
```

**Comment by beele** [comment]
- homebridge running on?
- camera hardware?
- is it working if you use camera-homebridge-ffmpeg
- logging

**Comment by matellis** [comment]
- Hardware: initially a 3B, I migrated to an RPI4 in case it was an ethernet limit - same result
- Camera hardware: UVC G4 Pro or UVC G3 Flex - same result
- Not sure what 'use camera-homebridge-ffmepg' means. I'm using https://github.com/homebridge-plugins/homebridge-camera-ffmpeg as the ffmpeg plugin. The feeds worked great with another homebridge plugin (protect2) but not sure if they were simply pointing HomeKit at an RTSP feed
- Logging: I enabled debug log; it shows the feed working in real time with a 1x "speed" (sometimes 1.01x), a start and a stop with no error. Reluctant to post full log as it has a lot of camera authorization stuff in it. This is the non-debug log when I select any camera. With debug on there's a once per second entry listing some stats with "speed" never being <1x:
```
[5/29/2020, 01:38:12] [Unifi protect cameras & motion sensors] Start streaming video from BGD Cottage Entrance with 640:360@15fps (132kBit)
[5/29/2020, 01:38:23] [Unifi protect cameras & motion sensors] Snapshot from BGD Cottage Entrance at 480:270
[5/29/2020, 01:38:23] [Unifi protect cameras & motion sensors] Stopped streaming
```

**Comment by beele** [comment]
Seems to be an issue with FFmpeg, A partial debug log would be very handy.
You are using both https://github.com/homebridge-plugins/homebridge-camera-ffmpeg and this plugin?
What I meant by using said url is too remove this plugin, or disable it. and test with the other one, It's the one my code for the camera logic is based on.
