### ISSUE TITLE
tensorflow install issue

### ISSUE THREAD

**Issue by MaverickC2** [beele/homebridge-unifi-protect-camera-motion#51]
5081 verbose cwd /home/pi
5082 verbose Linux 4.19.118-v7l+
5083 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "homebridge-unifi-protect-camera-motion" "-g" "--unsafe-perm=true"
5084 verbose node v12.18.1
5085 verbose npm  v6.14.5
5086 error code ELIFECYCLE
5087 error errno 1
5088 error @tensorflow/tfjs-node@1.2.11 install: `node scripts/install.js`
5088 error Exit status 1
5089 error Failed at the @tensorflow/tfjs-node@1.2.11 install script.
5089 error This is probably not a problem with npm. There is likely additional logging output above.
5090 verbose exit [ 1, true ]
pi@homebridge:~$ npm i @tensorflow/tfjs-node@1.2.11

> @tensorflow/tfjs-node@1.2.11 install /home/pi/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-1.2.11.tar.gz
* Downloading libtensorflow
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@1.2.11 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tensorflow/tfjs-node@1.2.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by beele** [comment]
I'm looking into fixing tensorflow issues for future releases.
As for this error, it looks like there's an invalid certificate, hopefully they renew it

**Comment by beele** [comment]
@MaverickC2 
Can you try with the beta build?
sudo npm i -g --unsafe-perm=true homebridge-unifi-protect-camera-motion@0.4.0-Beta.7
And please check the adjusted readme on this branch for config changes: https://github.com/beele/homebridge-unifi-protect-camera-motion/tree/feature/rework-camera-and-tfjs

**Comment by BadgerBadgerAndFox** [comment]
@beele is it possible to have an option to use an external AI engines API for the detection for those that are having trouble with tensorflow and have access to a GPU or VPU backed service like deepstack ai? https://deepstack.cc/

**Comment by beele** [comment]
@BadgerBadgerAndFox I'll have to have a look for that. 
However the beta build should have less issues with tensorflow

**Comment by tronny87** [comment]
> @BadgerBadgerAndFox I'll have to have a look for that.
> However the beta build should have less issues with tensorflow.
> I'm also not too keen with sending sensitive image data over the internet, it's the main reason the image detection is done on device.
> 
> Edit: I've taken a look at deepstack and this might be a good alternative to using the node tensorflow.

Would using deepstack finally make this plugin usable on non-AVX CPUs? (Like my Synology NAS)

If yes, sign me up if you need a tester. Lol

**Comment by beele** [comment]
I've looked into deepstack and it's not gonna be a solution.
It does not run on a rbpi without the use of an external usb accelerator
As for synology systems without AVX, I'm afraid these will not be supported. (If you could cross compile a version of tenforflow without AVX and feed that tar file into the plugin postinstall script)
