### ISSUE TITLE
Snapshot Saved Too Late

### ISSUE THREAD

**Issue by ntableman** [beele/homebridge-unifi-protect-camera-motion#54]
All the snapshots being saved are maybe 15 seconds after the motion - it is detecting my car (not moving) in the driveway to 96%, which seems reasonable.

But something it triggering it - most likely a car passing on the road - and that is what I want to capture, not a 15 second later image of my parked car.

Any idea on how to tune this plugin to help?

Thanks!

**Comment by beele** [comment]
This is literally mentioned in the readme...

> Previews in notifications are requested by the Home app, and can thus be "after the fact" and show an image with nothing of interest on it.
The actual motion detection is done with the snapshot that is requested internally.

But to provide an answer. The new beta version of the plugin uses a new way to add the camera's to homekit and will in 99% of cases provide a notification with the actual snapshot that was used to detect the motion.
