### ISSUE TITLE
(Asking for help, not a bug...) Compiling Tensorflow on a Synology NAS

### ISSUE THREAD

**Issue by tronny87** [beele/homebridge-unifi-protect-camera-motion#56]
So for months I used to use this plugin on my Raspberry Pi with my UniFi Protect setup and I used to love it, but when I abandoned the Pi for Homebridge use and migrated my entire Homebridge setup to my Synology 918+, I was unaware that this plugin would no longer be compatible.

As it was explained to me, the current prebuilt version of Tensorflow (needed for this plugin to work) is not compatible with the type of CPU in my NAS and needs to be compiled from scratch.

I found an alternative plugin that adds UniFi Protect cameras to HomeKit, and it works great for streaming the video and getting snapshots, however it does not support motion alerts

Now, I have tried to look for guides, reach out for help, and see if I can find any type of step-by-step guide that would help me achieve this, but for months, I've had no luck. I am not very command-line savvy and rely heavily on tutorials and guides to get my setup going and always try to learn as much as I can as I go along.

I know the easy thing to do would be simply go back to using the Pi for this plugin, but at this point this is no longer an option.

My ask is this.... if someone, anyone, has the time or generosity to guide me through compiling the Tensorflow / Canvas build needed for me to run this plugin in a Homebridge instance on my Synology NAS... I would be forever in your debt.

**Comment by beele** [comment]
I'm afraid compiling tensorflow from scratch is out of scope for this project.
I've tried this myself multiple times and issues always come up.
I'd just run it on a rbpi
