### ISSUE TITLE
HOOBS not finding any cameras

### ISSUE THREAD

**Issue by ilyesm** [beele/homebridge-unifi-protect-camera-motion#57]
Hi,

I am trying to install the plugin, and have followed all steps and included the script on the config.json, however in the logs I see the following:

22/07/2020, 17:27:01 The requested platform "UnifiProtectMotion" was not registered by any plugin.
22/07/2020, 17:27:01 Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.

Any insights as to what can be happening?

Also, I am using a UDM-Pro with the UniFi Protect controller installed, and when I access https://192.168.1.1:7443 (HTTPS Port), I see "An unrecoverable error has occurred!", could it be related to that?

Thanks.

**Comment by beele** [comment]
What node/homebridge version are you using?
What config are you using?
Did you install the prerequisites for node-canvas?

**Comment by ilyesm** [comment]
I am running HOOBS version 3.2.6, node version 12.16.3.

My config is below:
`{
            "platform": "UnifiProtectMotion",
            "plugin_map": {
                "plugin_name": "homebridge-unifi-protect-camera-motion"
            },
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "controller": "https://192.168.1.1:443",
                "controller_rtsp": "rtsp://192.168.1.1:7447",
                "username": "XXXXXXXXXX",
                "password": "XXXXXXXXXX",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": true,
                "enhanced_motion_score": 50,
                "enhanced_classes": [
                    "person"
                ],
                "save_snapshot": false,
                "debug": false
            },
            "googlePhotos": {
                "upload_gphotos": false,
                "auth_redirectUrl": "http://localhost:8080/oauth2-callback"
            },
            "videoConfig": {
                "maxStreams": 2,
                "maxWidth": 1024,
                "maxHeight": 576,
                "maxFPS": 15,
                "maxBitrate": 3000,
                "vcodec": "libx264",
                "packetSize": 376,
                "audio": false,
                "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp"
            }
        }`

I have installed all prerequisites as per the readme. Below is the return
`hoobs@rpi1:~ $ sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.6).
libgif-dev is already the newest version (5.1.4-3).
libjpeg-dev is already the newest version (1:1.5.2-2).
libpango1.0-dev is already the newest version (1.42.4-8~deb10u1).
librsvg2-dev is already the newest version (2.44.10-2.1+rpi1).
libcairo2-dev is already the newest version (1.16.0-4+rpt1).
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

I am unable to access https://192.168.1.1:7443, and was told by UBNT to use https://192.168.1.1:443. I do not know if this is connected in some way.

Thanks!

**Comment by ilyesm** [comment]
Hey,

I just checked the config, enabled RTSP on all cameras, and still get the error below when starting Hoobs/Homebridge.

`24/07/2020, 13:05:46 Loaded plugin "homebridge-unifi-protect-camera-motion".
24/07/2020, 13:05:46 The requested platform "UnifiProtectMotion" was not registered by any plugin.
24/07/2020, 13:05:46 Your config.json is requesting the platform "UnifiProtectMotion" which has not been published by any installed plugins.`

Thanks.

**Comment by askovi** [comment]
This issue is coming from the platform registration. I submitted a PR a while ago which was merged but the update hasn't been released: https://github.com/beele/homebridge-unifi-protect-camera-motion/pull/50
That will fix the "`The requested platform "UnifiProtectMotion" was not registered by any plugin.`" error

**Comment by ilyesm** [comment]
Hi @askovi , 

Thanks for getting back to me. Any idea on how long it'll take if it will be released at all, @beele ? Thanks!

**Comment by beele** [comment]
0.4.1 has been released
