### ISSUE TITLE
Tensorflow message

### ISSUE THREAD

**Issue by madrobby** [beele/homebridge-unifi-protect-camera-motion#61]
Getting this message:

```
============================
Hi there 👋. Looks like you are running TensorFlow.js in Node.js. 
To speed things up dramatically, install our node backend, which
binds to TensorFlow C++, by running npm i @tensorflow/tfjs-node,
or npm i @tensorflow/tfjs-node-gpu if you have CUDA. Then call
require('@tensorflow/tfjs-node'); (-gpu suffix for CUDA) at the start
of your program. 

Visit https://github.com/tensorflow/tfjs-node for more details.
============================
```

I think it's from thius plugin. Would be good if this is supported! FWIW I'm running on a Mac Mini that _does not_ have CUDA support.

**Comment by beele** [comment]
This message is in error, I don't know why, but it can be ignored. If the C++ binding was not working and tensorflow would be running in pure js mode, the performance would be 10x slower, you'd notice ;)
