### ISSUE TITLE
 After installing, homebridge fails to start

### ISSUE THREAD

**Issue by bls8486** [beele/homebridge-unifi-protect-camera-motion#7]
Running homebridge as a service on ubuntu 18.04 on small form factor PC.  Only other plugin is homebridge-config-ui-x.  After install, get same core dump when starting homebridge.  Tried with valid config and with no config defining homebridge-unifi-protect-motion-sensors.  Install seems to go fine even time.

Jan 07 09:54:47 homebridge-01b systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 07 09:54:47 homebridge-01b systemd[1]: Started Homebridge.
Jan 07 09:54:48 homebridge-01b homebridge[12175]: [1/7/2020, 9:54:48 AM] Loaded config.json with 0 accessories and 1 platforms.
Jan 07 09:54:48 homebridge-01b homebridge[12175]: [1/7/2020, 9:54:48 AM] ---
Jan 07 09:54:49 homebridge-01b homebridge[12175]: [1/7/2020, 9:54:49 AM] ---
Jan 07 09:54:49 homebridge-01b homebridge[12175]: [1/7/2020, 9:54:49 AM] Loaded plugin: homebridge-config-ui-x
Jan 07 09:54:49 homebridge-01b homebridge[12175]: [1/7/2020, 9:54:49 AM] Registering platform 'homebridge-config-ui-x.config'
Jan 07 09:54:49 homebridge-01b homebridge[12175]: [1/7/2020, 9:54:49 AM] ---
Jan 07 09:54:52 homebridge-01b systemd[1]: homebridge.service: Main process exited, code=dumped, status=4/ILL
Jan 07 09:54:52 homebridge-01b systemd[1]: homebridge.service: Failed with result 'core-dump'.
Jan 07 09:54:55 homebridge-01b systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Jan 07 09:54:55 homebridge-01b systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 1.

**Comment by bls8486** [comment]
@beele.  Sorry, forgot to tag you.

**Comment by beele** [comment]
Config?
Node version?

**Comment by bls8486** [comment]
This is from a fresh install on a new homebridge server
Node V: 12.14.0

fails with a base config with only config-ui-x defined
`{

    "bridge": {
        "name": "Homebridge",
        "username": "xxxxxxxxx",
        "port": xxxxxx,
        "pin": "xxxxxxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        }
    ]
}`

also fails with this

`{

    "bridge": {
        "name": "Homebridge",
        "username": "xxxxxxxxxxxxx",
        "port": xxxxxx,
        "pin": "xxxxxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
		{
            "platform": "Unifi-Protect-Camera-Motion",
            "name": "Unifi protect cameras & motion sensors",
            "unifi": {
                "controller": "xxxxxxxxxxxxxxxxxxxxxxxxx",
                "controller_rtsp": "xxxxxxxxxxxxxxxxxx",
                "username": "xxxxxxxxxxx",
                "password": "xxxxxxxxxx",
                "motion_interval": 5000,
                "motion_repeat_interval": 30000,
                "motion_score": 50,
                "enhanced_motion": true,
                "enhanced_motion_score": 50,
                "enhanced_classes": [
                    "Person"
                ],
                "debug": false,
                "save_snapshot": true
            },
            "videoConfig": {
                "vcodec": "h264",
                "audio": false,
                "maxStreams": 2,
                "maxWidth": 1024,
                "maxHeight": 576,
                "maxFPS": 15,
                "mapvideo": "0:1",
                "mapaudio": "0:0"
            }
        }
    ]
}`

**Comment by beele** [comment]
I see you are using node 12, I've only tested this with the node versions mentioned in the readme (10.x.x and 11.x.x)
Please try with a different node version and see if it works

**Comment by bls8486** [comment]
I uninstalled homebridge and all plugins, then reverted to 10.x.x.  I was seeing N-API issues after that. I decided to remove the new plugin go with my old configuration.  Thanks for your help.  I may spin up another server to test this in the future.

**Comment by beele** [comment]
@bls8486 Node 12 should now work correctly. I've made some updates in the latest version of the plugin that should fix these issues.
