### ISSUE TITLE
Incorrect Aspect Ratio for Doorbell Snapshot

### ISSUE THREAD

**Issue by shnhrrsn** [beele/homebridge-unifi-protect-camera-motion#70]
The G4 Doorbell is 1600x1200 (4:3) — it looks like snapshots are being forced to 1280x720 (16:9) regardless of device type so they appear stretched in Home.app.

**Comment by JJJ** [comment]
I noticed this, too. Not only the snapshot, but the video feed as well.

I'm not certain if this is configurable. I half assumed HomeKit always used 16:9 for everything.

**Comment by beele** [comment]
I'll try and see if it's possible, I would assume that it would just display the stream/snapshot as is, but ffmpeg can probaly be set to letter/pillarbox the video/photo

**Comment by JJJ** [comment]
Testing 0.4.3 beta 3 here, no change:

## Feed
![jjj-sc-2020-08-23 at 22 36 06@2x](https://user-images.githubusercontent.com/88951/91001418-493d6380-e591-11ea-93c7-6ab6c7f68d9e.png)

## Thumbnails
![jjj-sc-2020-08-23 at 22 36 56@2x](https://user-images.githubusercontent.com/88951/91001426-4b072700-e591-11ea-8003-0f05f24ef7b3.png)

My config already had those keys set, plus others. Are you saying to remove everything else? Here's mine:

```
"videoConfig": {
    "vcodec": "h264_omx",
    "audio": true,
    "maxStreams": 3,
    "maxWidth": 3840,
    "maxHeight": 2160,
    "maxFPS": 60,
    "mapvideo": "0:1",
    "mapaudio": "0:0",
    "maxBitrate": 3000,
    "packetSize": 376,
    "additionalCommandline": "-protocol_whitelist https,crypto,srtp,rtp,udp -loglevel verbose"
}
```

**Comment by beele** [comment]
@JJJ You should try with only the small videoConfig like the one I posted above.

**Comment by JJJ** [comment]
@beele holy moly that is a HUGE improvement.

* Video quality is immensely improved
* Aspect ratio is correct
* Video play speed is the same

## Feed
![jjj-sc-2020-08-24 at 12 15 53@2x](https://user-images.githubusercontent.com/88951/91075464-b984cd00-e603-11ea-96db-a0bdb0b68859.png)

## Thumbnails
<img width="453" alt="jjj-sc-2020-08-24 at 12 16 21@2x" src="https://user-images.githubusercontent.com/88951/91075480-c30e3500-e603-11ea-9461-a69017c64955.png">

**Comment by JJJ** [comment]
First weird new error in homebridge logs. 

![53FD9F8C-6498-420D-AEC1-14A3742BA7C6](https://user-images.githubusercontent.com/88951/91120190-b36e0b00-e65a-11ea-831d-bb73855a559b.jpeg)

**Comment by beele** [comment]
I have a fix for that issue coming up, the strange thing is that I don't get that error.
Are any of your cameras off (or disconnected, or....).
I have one camera that is mostly off but I still get a snapshot from the protect url (be it an older image off when it was last on and queried for a snapshot)

**Comment by beele** [comment]
@JJJ Can you try with:
`sudo npm i -g homebridge-unifi-protect-camera-motion@0.4.3-beta.4 --unsafe-perm=true`

**Comment by JJJ** [comment]
Will test today and report back.

It's plausible that the cameras or UDM Pro rebooted (like after updates?) but they were all online and functioning at the time of the error. I could access them fine via the official protect app, but not via Home.

**Comment by JJJ** [comment]
@beele so far, so good.

* Installed beta 4
* Rebooted my Raspberry Pi
* Stress tested by loading feeds from Home app on Mac/iPad/iPhone in rapid succession - no errors yet

**Comment by JJJ** [comment]
@beele unsure if related, but I've had it happen twice today where video & snapshots simply stop responding.

Last night, Unifi Protect updated to 1.14.12-beta.3, which may also be contributing. Since I have no facts, this is simply to report what I'm seeing, and I'll update as I learn more.

**Comment by beele** [comment]
@JJJ Can you try with the latest beta, I've reworked how video streams are handled.
`sudo npm i -g --unsafe-perm=true homebridge-unifi-protect-camera-motion@0.4.3-beta.8`
