### ISSUE TITLE
Audio Support?

### ISSUE THREAD

**Issue by dVIAN13** [beele/homebridge-unifi-protect-camera-motion#8]
nice work @beele ! I was wondering if you had an estimate on when you think audio will be supported?

**Comment by beele** [comment]
I think if you build ffmpeg with the following instructions that audio should just work: https://gist.github.com/milankragujevic/bd38d796ea6eea27f229216d75d6c202

I haven't tested this myself yet though.

**Comment by beele** [comment]
The newest version supports audio (see the updated readme)
