### ISSUE TITLE
Unifi protect port & RTSP port

### ISSUE THREAD

**Issue by alezanott** [beele/homebridge-unifi-protect-camera-motion#81]
Since the latest update to UniFi Protect it seems that something has changed regarding the port used by the controller. Now after the IP address of the controller you don't find no more the `7443` port, but instead `/protect`. It seems that this creates an issue in the configuration of the plugin, currently running on the latest version of Homebridge. Regarding the RTSP stream, up to now it can be only used the unsecure one? Waiting for your reply @beele thank you

**Comment by beele** [comment]
Hi @alezanott, can you try with the latest beta version? I'm running that and have no issues.
https://www.npmjs.com/package/homebridge-unifi-protect-camera-motion/v/0.4.3-beta.12

**Comment by alezanott** [comment]
Still no clue whats wrong @beele . I have also enabled the verbose mode to understand better what is not working but the plugin just tell me that the configuration is not valid. I have upgraded to the last beta version. I think that the issue is maybe caused by the port that has changed for the UniFi controller part.

**Comment by alezanott** [comment]
Hi @beele, solved! UniFi was not working properly. Had just upgraded the firmware of my CK+ a while ago and now works everything fine on the new beta version of the plugin.
