### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by WiehanVanNiekerk** [beele/homebridge-unifi-protect-camera-motion#89]
**Describe the bug**
I can get this working with a udm pro setup and hoobs on raspberry pi.

**Specifications**
- Raspberry pi 3
-  UDM Pro (For PROTECT)
-  G3 Flex Camera
- Hoobs

**Comment by WiehanVanNiekerk** [comment]
This is my error: W tensorflow/core/framework/allocator.cc:107] Allocation of 8640000 exceeds 10% of system memory.

**Comment by beele** [comment]
Hoobs is not supported, and the error is a warning and can be ignored
