### ISSUE TITLE
Support UniFi OS (UDM Pro on versions >1.6)

### ISSUE THREAD

**Issue by jonbloom** [beele/homebridge-unifi-protect-camera-motion#9]
The latest version of the UDM Pro firmware proxies all requests to controllers, allowing SSO to all controllers hosted on it. It is no longer possible to authenticate directly to Protect. 

Per UI-taka on the Ubiquiti discord: 

> you need to auth to the device first via /api/login, then the actual paths to protect are different, prefixed with /proxy/protect

From what I've seen, UniFi OS will be coming to the Cloud Key Gen 2 Plus, as well as the UniFi NVR, so this will be a hurdle that will have to be crossed.

**Comment by beele** [comment]
I'll keep an eye on this. I only have a cloud key gen 2+
So I'll have to wait to implement and test this till it rolls out on that device.
Others are free to already test this with the UDM Pro and open a pull request.

**Comment by jonbloom** [comment]
@beele I forker the other Protect homebridge plugin and updated it to support UniFi OS here: https://github.com/jonbloom/homebridge-unifi-protect2

It retails backwards compatibility with the Cloud Key Gen2 Plus, too.

**Comment by beele** [comment]
@jonbloom Thx, I'll have a look and will implement the changes here

**Comment by jonbloom** [comment]
Sounds good! I just made a PR to the repo that I forked, so that should go in. Let me know if you have any questions on how I implemented the changes. It should be pretty easy. 

I'd have made a PR here but I'm not super familiar with TypeScript.

**Comment by acesarewld** [comment]
> @beele I forked the other Protect homebridge plugin and updated it to support UniFi OS here: https://github.com/jonbloom/homebridge-unifi-protect2
> 
> It retails backwards compatibility with the Cloud Key Gen2 Plus, too.

John this is GREAT! I am trying to install it into Homebridge but I'm really not sure what to do. When I use the GUI I can see I am running the hjdhjd version and not yours... how exactly do I go about replacing what I have now with your version that supports the UDM?

**Comment by jonbloom** [comment]
@acesarewld First off, it's Jon. It’s right there!

I submitted a pull request to that other project so it's up to them to merge in my changes. If they don't within a few more days, I'll just publish it myself under a different plugin name.

**Comment by acesarewld** [comment]
> @acesarewld First off, it's Jon. It’s right there!
> 
> I submitted a pull request to that other project so it's up to them to merge in my changes. If they don't within a few more days, I'll just publish it myself under a different plugin name.

Jon -- I corrected it in my other message and do apologize! My name is Geoff (with a 'G') and in e-mail replies people call me 'Jeff' -- and I feel the same way -- IT'S RIGHT THERE! It was 3AM or so when I wrote that and I was pretty tired after rebuilding some VM's - sorry again, but also THANK YOU! Awesome work and looking forward to it making it into the real project or seeing yours come out.

Thanks (and sorry) again! 
--Geoff (not Jeff) 😝

**Comment by crxporter** [comment]
Jon and Geoff-

Count me in as another who’s ready to see this ready for UDM Pro. 

-Garrett (with 2 r’s and 2 t’s)

**Comment by beele** [comment]
@jonbloom 
I've just made the first changes (untested) for supporting both the old way of working and the new UnifiOS method.

Code in https://github.com/beele/homebridge-unifi-protect-camera-motion/tree/feature/unifi-os-support

**Comment by janthony6** [comment]
how do i install the unifi-os branch onto an rpi instead of the main one?

**Comment by beele** [comment]
Merged into master and available on release 0.1.1 on npm
This is however untested with Unifi OS since I don't have access to a UDM

**Comment by jonbloom** [comment]
@beele Hi, I'm just getting around to testing this.
I'm getting the following error: 
`[Unifi protect cameras & motion sensors] Cannot get cameras: Error: ERROR: Could not enumerate motion sensors: Error: Authentication failed: {}`

Is there an easy way to get more detailed debugging logs? This is with `debug: true`.

**Comment by jonbloom** [comment]
@beele Looks like the  one thing my plugin was doing that yours is not is keeping the cookies between the initial login request and the bootstrap call. The login request sets a cookie `TOKEN` which is a JWT token to use in subsequent requests. I think if that's added in, then we'll be good to go on UDM Pro.

**Comment by jonbloom** [comment]
Looking at [this](https://github.com/beele/homebridge-unifi-protect-camera-motion/blob/3cc7554d38c5a01e09ef08c33a448d6b6dd35ab9/src/unifi/unifi.ts#L84) line, and decoding the JWT token, the new session duration is only one hour. Each subsequent request updates the cookie with a new expiration on the JWT token. Perhaps there should be a cookie jar associated with the session that can be continually updated and used for each request?

**Comment by beele** [comment]
@jonbloom I'll have a look! Thx for the info

**Comment by jonbloom** [comment]
@beele No problem. There's also the new UVC-G4-Doorbell to support that generates a new kind of event, `ring`. I need to check if that ends up in the events  API, or just the logfile on the server.

**Comment by beele** [comment]
Active development for Unifi OS support is being handled in this ticket: https://github.com/beele/homebridge-unifi-protect-camera-motion/issues/20

**Comment by beele** [comment]
Closing in favour of #20
